sonar.projectKey=sonyrich_HD
sonar.organization=sonyrich
sonar.host.url=https://sonarcloud.io
sonar.projectName=TaskManager API
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,logs/**
sonar.test.inclusions=tests/**/*.test.js
sonar.sourceEncoding=UTF-8